# Generated by Django 3.2.8 on 2021-12-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
