# Generated by Django 3.2.8 on 2021-12-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211211_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
